services:
    simpleweb.saas.subscription.manager:
        class: %simpleweb.saas.subscription.manager.class%
        arguments:
            - %simpleweb.saas.subscription.class%
            - @event_dispatcher

parameters:
    simpleweb.saas.subscription.manager.class: Simpleweb\SaaSBundle\Manager\SubscriptionManager
